services:
  java-app:
    image: arman04/java-maven-app:jma-1.0.0
    ports:
      - "8080:8080"
    environment:
      - DB_USER=user
      - DB_PWD=pass123
      - DB_SERVER=mysql
      - DB_NAME=my_app_db
    container_name: my-java-app
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my_app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass123
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
    container_name: myadmin
volumes:
  mysql-data:
    driver: local
